{
    premades: "?", # '?' for asking | 'n' for sites.txt | '1' for http/s | '2' for socks4 | '3' for socks5

    removewebsites: "?", # Removes not connectable websites | '?' for asking | 'y' or 'n'

    removeproxyless: "?", # Removes websites if no proxies are found | '?' for asking | 'y' or 'n'

    threads: "?" # '?' for asking | '[Threadcount]'
}